### ISSUE TITLE
Not sure how to use it

### ISSUE THREAD

**Issue by chandangm** [anilabhadatta/educative.io_scraper#15]
Downloaded the packages from releases, running both executable at the same time, not sure what's the correct config, but have created a text file with url links in it, was able to login in through the code, but then when you start scrapping it says: **Main Exception local variable 'driver' referenced before assignment**

Anything you want me to try apart from what you've mentioned in the readme? A little help would be appreciated.

**Comment by anilabhadatta** [comment]
Don't use the releases since I have not updated the releases to the latest version yet.
Clone the repo,
Download the respective Chrome Binary for your operating system from releases section and extract it inside Chrome-bin folder,
Run python chromedriver.py in one terminal
Run python educative_scraper.py in the second terminal
The rest should work fine.
If possible create a video demonstration.

**Comment by chandangm** [comment]
Did that, same issue. 
Need help with creating config file, when it's asking for URL, should i be pasting the url for the course or the file path for url containing text file? Tried with both and still have the same issue.

**Comment by anilabhadatta** [comment]
File path -> C:/urls.txt

**Comment by anilabhadatta** [comment]
@chandangm is your issue fixed?

**Comment by arnabs542** [comment]
@anilabhadatta hi bro I have a quey. Where does the log.txt file gets saved?

**Comment by anilabhadatta** [comment]
@arnabs542 save path
