### ISSUE TITLE
Terrible documentation

### ISSUE THREAD

**Issue by jsDobromir** [anilabhadatta/educative.io_scraper#16]
I appreciate your efforts to create this, but have nod idea how to start it, the explanation is more confusing than helpful.

**Comment by anilabhadatta** [comment]
Clone the repo,
Download the respective Chrome Binary for your operating system from the releases section and extract it inside the Chrome-bin folder,
![image](https://user-images.githubusercontent.com/48487849/190623114-493fc389-5ada-44f5-9065-fd7178b44d45.png)

Run python chromedriver.py in a terminal
Run python educative_scraper.py in a separate terminal

Generate the config for first time use.
For urls.txt file path, add the full path to URLs.txt file
eg, C:/Desktop/urls.txt

In URLs txt file you should add the URLs of the first topic from a specific course.
eg ; ![image](https://user-images.githubusercontent.com/48487849/190623603-3b044d87-bdfe-4e33-aca4-208d1b2cf8e8.png)

In urls.txt file it should show like this;
![image](https://user-images.githubusercontent.com/48487849/190623713-3313a14a-9c33-4c7b-956c-e8bcf001e95f.png)
Starting Index is only required if you are scraping from a particular topic otherwise not required.

**Comment by jsDobromir** [comment]
Tnx for answer.
I am on Ubuntu and getting this error: Main Exception Message: unknown error: no chrome binary at /home/dobromir/Documents/env/educative.io_scraper-master/Chrome-bin/linux/chrome/chrome

![Screenshot from 2022-09-16 14-06-10](https://user-images.githubusercontent.com/55588849/190625650-5740ae96-5803-45ce-80a1-f9370ae4afdd.png)

**Comment by jsDobromir** [comment]
After creating /linux/chrome/chrome and dropping the chrome binary there, getting this error: **Main Exception Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/dobromir/Documents/env/educative.io_scraper-master/Chrome-bin/linux/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
**

**Comment by anilabhadatta** [comment]
which chrome-bin did you download?
and is your ubuntu running on arm64 or amd64 architecture?

**Comment by jsDobromir** [comment]
Its amd64, restarted, same issue. Thats what I get when I try to open it in the browser.

![Screenshot from 2022-09-16 14-38-00](https://user-images.githubusercontent.com/55588849/190630618-94860057-3c28-4bc6-89d4-352eaf77e6e0.png)

**Comment by anilabhadatta** [comment]
@jsDobromir Let me check, i may need you to share your screen

**Comment by anilabhadatta** [comment]
@jsDobromir Is your issue resolved and should I close this issue?
