### ISSUE TITLE
name 'unicode' is not defined

### ISSUE THREAD

**Issue by keiji11** [anilabhadatta/educative.io_scraper#2]
Hi, there is an error when I do the scraping of course. Why?
![scrape_educative_error](https://user-images.githubusercontent.com/43145711/165531671-58c697ef-4e9d-4796-809d-7ab85ba09307.png)

**Comment by anilabhadatta** [comment]
@keiji11 since the scraper worked before, could u test with any other course
Also if possible then send me the link of the course causing issue.
And i guess u are using linux?
Also please use the chrome binaries and drivers provided in releases.
Don't update from any other source as different version may cause different types of issues.

**Comment by anilabhadatta** [comment]
@keiji11 okay, i think i made the releases for debian based linux so that may cause issues with arch linux.
If you can contribute in releases , it would be a great help.
Thank you and I am closing the issue

**Comment by keiji11** [comment]
Alright, Thank you to you
