### ISSUE TITLE
Main Exception local variable 'driver' referenced before assignment

### ISSUE THREAD

**Issue by sachamorgese** [anilabhadatta/educative.io_scraper#5]
Hey there,

I was unable to use the executable for MacOS nor Windows, so I decided to check out the repo and see if I were able to make it work from there.

I followed everything in the instructions and was able to launch chromium and authenticate, but when it's time to start scraping, it fails with this error:

`Main Exception local variable 'driver' referenced before assignment`

I did the same for both Windows and MacOS. Same result. Can launch the driver, can login with chromium, then this error happens.

**Comment by sachamorgese** [comment]
I found the issue. Or better, I found where the error is happening and why it isn't actually showing what the problem is.

In `educative_scraper.py` you have from line 938:

```
except Exception as e:
        driver.quit()
        print("Exception, Driver exited", e)
        raise Exception(e)
```

I think `driver.quit()` for some reasons prevents the error from being shown here.
If you put it after the print statement, you can see the actual error from that page.

My problem is the lack of text file. The instructions aren't clear, so I ended up putting the link directly in there instead of the link to the file.

**Comment by anilabhadatta** [comment]
@sachamorgese To scrap manually, run chromedriver.py and then educative_scraper.py
Make sure that you have extracted the Chrome-binaries provided in releases for respective OS.
Since you were able to authenticate your account, so I assume the chrome binaries are correctly placed.
Next you have to create a simple text file ".txt" and paste the link of the first topic in a course (displaed in README.md).
You can also provide a number before the link to specify the starting index of the topics. (Helps for resume feature, if scraper stops for some reason then you can just copy/paste the index URL from log.txt to continue scraping from where it was left previously)
Next you have to generate a config, where you have to specify the path to text file and the save directory path.
Then authenticate your educative account 
Then start scraping.
Recommended - You headless = True for scraping, And don't run multiple scrapers as it may cause captcha issues.
